In [14]:
import os
import sys

root_dir = os.path.dirname(os.path.dirname(os.path.realpath('__file__')))
model_dir = os.path.join(root_dir, "model")
sys.path.append(root_dir)
sys.path.append(model_dir)

import time
import json
import numpy as np
import pandas as pd

import hoho_utils

In [15]:
hoho_utils.INDEXS_2_PIECES

'KARBNPCkarbnpc'

In [10]:
data_dir = "../output/data"
file_list = os.listdir(data_dir)
file_count = len(file_list)
item_list = list()

print(f"file_count: {file_count}")

for i, filename in enumerate(file_list):
    file_path = os.path.join(data_dir, filename)
    with open(file_path, "r") as file:
        json_str = file.read()
        matches = json.loads(json_str)
        match_count = len(matches)
        
        for j, match in enumerate(matches):
            print(f"match: {match}")
#             break
            
            mid = i * file_count + j
            base_id =  f"{int(time.time())}"
            for k, round in enumerate(match):
                match_id = f"{mid}"
                round_id = f"{base_id}{k}"
                state = round[0]
                action = round[2]
                next_state = round[3]
                chapture_list = round[6]
                chaptures = ','.join(chapture_list)
                chapture_reward = round[7]
                
                win = 0
                done = round[5]
                if "K" in chapture_list:
                    win = -1
                    done = True
                elif "k" in chapture_list:
                    win = 1
                    done = True
                    
                round_dict = {"match_id": match_id,
                              "round_id": round_id,
                              "state": state,
                              "action":action,
                              "next_state": next_state,
                              "done": done,
                              "chaptures": chaptures,
                              "chapture_reward": chapture_reward,
                              "win": win}
                item_list.append(round_dict)
                
                if win == 1 or win == -1:
                    break

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



match: [['RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04040404040404041, 0.010101010101010102, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [28]:
data = pd.DataFrame(item_list)

In [29]:
data

match_id     round_id                                              state  \
0           0  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
1           0  16922826811  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   
2           1  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
3           1  16922826811  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   
4           2  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
...       ...          ...                                                ...   
2528      584  16922826824  RNBc2B2/5K3/2C6/P1P1P1P1P/1C7/9/p1p1p1p1p/1c7/...   
2529      584  16922826825  RNBc2B2/5K3/2C6/P1P1P1P1P/3C5/9/p1p1p1p1p/1c4n...   
2530      584  16922826826  RNBc2B2/5K3/2C6/P1P1P1P1P/5C3/9/p1p1p1p1p/1c4n...   
2531      584  16922826827  RNBc2B2/5K3/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c4n2...   
2532      584  16922826828  1NBc2B2/R4K1r1/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c...   

     action                                         next_state   done  \
0      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
1      h2g2  RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...   True   
2      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
3      h2g2  RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...   True   
4      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
...     ...                                                ...    ...   
2528   b4d4  RNBc2B2/5K3/2C6/P1P1P1P1P/3C5/9/p1p1p1p1p/1c7/...  False   
2529   d4f4  RNBc2B2/5K3/2C6/P1P1P1P1P/5C3/9/p1p1p1p1p/1c4n...  False   
2530   f4f5  RNBc2B2/5K3/2C6/P1P1P1P1P/9/5C3/p1p1p1p1p/1c4n...  False   
2531   a0a1  1NBc2B2/R4K3/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c4n...  False   
2532   c2d2  1NBc2B2/R4K1r1/3C5/P1P1P1P1P/9/5Cp2/p1p1p3p/1c...   True   

     chaptures  chapture_reward  win  
0            N            -6.28    0  
1            K            -4.92   -1  
2            N            -6.28    0  
3            K            -4.92   -1  
4            N            -6.28    0  
...        ...              ...  ...  
2528                       0.00    0  
2529                       0.00    0  
2530                       0.00    0  
2531                       0.00    0  
2532         K            -4.92   -1  

[2533 rows x 9 columns]

In [30]:
data.dtypes

match_id            object
round_id            object
state               object
action              object
next_state          object
done                  bool
chaptures           object
chapture_reward    float64
win                  int64
dtype: object

In [31]:
data["win"].map(lambda x: 1 if x != 0 else 0)

0       0
1       1
2       0
3       1
4       0
       ..
2528    0
2529    0
2530    0
2531    0
2532    1
Name: win, Length: 2533, dtype: int64

In [32]:
data["converted"] = data["win"].apply(lambda x: 1 if x != 0 else 0)

In [33]:
data

match_id     round_id                                              state  \
0           0  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
1           0  16922826811  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   
2           1  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
3           1  16922826811  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   
4           2  16922826810  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
...       ...          ...                                                ...   
2528      584  16922826824  RNBc2B2/5K3/2C6/P1P1P1P1P/1C7/9/p1p1p1p1p/1c7/...   
2529      584  16922826825  RNBc2B2/5K3/2C6/P1P1P1P1P/3C5/9/p1p1p1p1p/1c4n...   
2530      584  16922826826  RNBc2B2/5K3/2C6/P1P1P1P1P/5C3/9/p1p1p1p1p/1c4n...   
2531      584  16922826827  RNBc2B2/5K3/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c4n2...   
2532      584  16922826828  1NBc2B2/R4K1r1/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c...   

     action                                         next_state   done  \
0      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
1      h2g2  RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...   True   
2      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
3      h2g2  RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...   True   
4      f0e1  RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...  False   
...     ...                                                ...    ...   
2528   b4d4  RNBc2B2/5K3/2C6/P1P1P1P1P/3C5/9/p1p1p1p1p/1c7/...  False   
2529   d4f4  RNBc2B2/5K3/2C6/P1P1P1P1P/5C3/9/p1p1p1p1p/1c4n...  False   
2530   f4f5  RNBc2B2/5K3/2C6/P1P1P1P1P/9/5C3/p1p1p1p1p/1c4n...  False   
2531   a0a1  1NBc2B2/R4K3/2C6/P1P1P1P1P/9/5Cp2/p1p1p3p/1c4n...  False   
2532   c2d2  1NBc2B2/R4K1r1/3C5/P1P1P1P1P/9/5Cp2/p1p1p3p/1c...   True   

     chaptures  chapture_reward  win  converted  
0            N            -6.28    0          0  
1            K            -4.92   -1          1  
2            N            -6.28    0          0  
3            K            -4.92   -1          1  
4            N            -6.28    0          0  
...        ...              ...  ...        ...  
2528                       0.00    0          0  
2529                       0.00    0          0  
2530                       0.00    0          0  
2531                       0.00    0          0  
2532         K            -4.92   -1          1  

[2533 rows x 10 columns]

In [34]:
data.to_excel("./hoho_chess_data.xlsx", index = False)

In [1]:
from sentence_transformers import SentenceTransformer, util

In [4]:
model = SentenceTransformer("sentence-transformers/multi-qa-mpnet-base-dot-v1")

In [6]:
s = "RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr"
s_emb = model.encode(s)
s_emb.shape

(768,)

In [12]:
s2 = "RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr"
s2_emb = model.encode(s2)
util.pytorch_cos_sim(s_emb, s2_emb)

tensor([[0.9940]])

In [29]:
def encode_pieces_one_hot(pieces):
    result = np.zeros(len(hoho_utils.INDEXS_2_PIECES))
    for p in pieces:
        index = hoho_utils.PIECES_2_INDEX[p]
        result[index] = 1
        
    return result



encode_pieces_one_hot(["N",'K'])

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
def encode_board_state(board_state, model):
    return model.encode(board_state)

encode_board_state(s, model)

array([ 2.03293446e-03, -3.99510771e-01, -3.94667536e-01,  4.49471176e-02,
       -9.08530280e-02, -1.48731381e-01,  9.34650302e-02,  3.34188521e-01,
       -6.87410980e-02,  1.35018393e-01,  1.58541668e-02,  2.25815892e-01,
        1.38883173e-01,  3.95828858e-02, -9.61677916e-03, -5.61620574e-03,
       -8.90335720e-03,  2.37791002e-01,  7.85450786e-02, -1.53406963e-01,
       -2.25123227e-01,  3.49796981e-01, -2.74773072e-02,  1.37449550e-02,
       -3.41288149e-02,  1.33264333e-01,  1.73145995e-01,  1.04285561e-01,
       -1.66571021e-01,  4.47820276e-02, -7.02413870e-03,  1.54150456e-01,
       -3.46533298e-01,  1.00070171e-01, -9.44488784e-05, -1.30628109e-01,
        1.15475096e-01, -3.07032615e-02, -2.77922630e-01,  2.90936172e-01,
       -1.09065637e-01,  1.44090533e-01, -3.41941118e-01, -2.43078932e-01,
       -1.56595379e-01,  2.06337087e-02,  1.18754156e-01,  1.61616653e-01,
        3.47181112e-01,  3.04221008e-02,  4.44022298e-01, -5.36740609e-02,
        1.83195006e-02, -

In [ ]:
def features_for_logistic_regression(df):
    