In [1]:
import sys, os

root_dir = os.path.dirname(os.path.dirname(os.path.realpath('__file__')))
sys.path.append(root_dir)

import random
import pandas as pd
import numpy as np

from model.hoho_dqn import *
from model.hoho_cchessgame import *
from model.hoho_agent import *

In [2]:
gamma = 0.99
lr = 5e-5
epsilon = 0.1

dqn = DQN(ACTION_DIM, lr, gamma, epsilon, 100, DEVICE)
state = INIT_BOARD_STATE
for i in range(100):
    action = dqn.take_action(state)
    print(f"    action: {action}")

random action!
    action: ('a3a4', array([0., 0., 0., ..., 0., 0., 0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
random action!
    action: ('e0e1', array([0., 0., 0., ..., 0., 0., 0.]))
argmax action!
    action: ('h2h6', array([-0., -0., -0., ..., -0., -0., -0.]))
argmax action!
    action: ('h2h6', array([-0., -0.,

In [3]:
dqn.printModel()

[2023-09-19 09:38:50,323][hoho_dqn.py][line:220][INFO] QNetwork(
  (board_layer): BoardPlaneLayer(
    (conv1): Conv2d(14, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (res0): ResidualBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (res1): ResidualBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=Fa

In [3]:
file_path = "./outputs/hoho_chess_data_20230915000911.xlsx"
data = pd.read_excel(file_path)

In [4]:
data

match_id         round_id  \
0         0-0   16947077516060   
1         0-0   16947077516061   
2         0-1   16947077516070   
3         0-1   16947077516071   
4         0-2   16947077516080   
...       ...              ...   
6601    63-24  169470775425018   
6602    63-24  169470775425019   
6603    63-24  169470775425020   
6604    63-24  169470775425021   
6605    63-24  169470775425022   

                                                  state action  \
0     RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   f0e1   
1     RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   h2g2   
2     RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   f0e1   
3     RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   h2g2   
4     RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   f0e1   
...                                                 ...    ...   
6601   6B2/4K4/1p7/P1c1P3P/9/6c2/p3p1n1p/n8/9/1rbakab1r   e3e4   
6602  6B2/4K4/1p7/P1c5P/1r2P4/6c2/p3p1n1p/n8/9/2bakab1r   g0e2   
6603  9/4K4/1p2B4/P1c5P/1r2P4/6c2/p3p1n1p/n8/9/2bakabr1   e1d1   
6604    9/3K5/1p2B4/P1c5P/4r4/6c2/p3p1n1p/n8/9/2bakabr1   d1d2   
6605     9/9/1p1KB4/P1c5P/3r5/6c2/p3p1n1p/n8/9/2bakabr1   d2d1   

                                             next_state  done chaptures  \
0     RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...     0         N   
1     RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...     1         K   
2     RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...     0         N   
3     RNBAK1BcR/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...     1         K   
4     RNBAK1BNR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...     0         N   
...                                                 ...   ...       ...   
6601   6B2/4K4/1p7/P1c5P/4P4/6c2/p3p1n1p/n8/9/1rbakab1r     0       NaN   
6602  9/4K4/1p2B4/P1c5P/1r2P4/6c2/p3p1n1p/n8/9/2bakab1r     0       NaN   
6603  9/3K5/1p2B4/P1c5P/1r2P4/6c2/p3p1n1p/n8/9/2bakabr1     0         P   
6604     9/9/1p1KB4/P1c5P/4r4/6c2/p3p1n1p/n8/9/2bakabr1     0       NaN   
6605    9/3K5/1p2B4/P1c5P/3r5/6c2/p3p1n1p/n8/9/2bakabr1     1         K   

      chapture_reward  win  converted                    jid  
0                -2.0    0          0     0-0_16947077516060  
1              -100.0   -1          1     0-0_16947077516061  
2                -2.0    0          0     0-1_16947077516070  
3              -100.0   -1          1     0-1_16947077516071  
4                -2.0    0          0     0-2_16947077516080  
...               ...  ...        ...                    ...  
6601              0.0    0          0  63-24_169470775425018  
6602              0.0    0          0  63-24_169470775425019  
6603             -1.0    0          0  63-24_169470775425020  
6604              0.0    0          0  63-24_169470775425021  
6605           -100.0   -1          1  63-24_169470775425022  

[6606 rows x 11 columns]

In [31]:
rb = ReplayBuffer.load_from_dir("../output/data")

In [32]:
rb.size()

23

In [33]:
print(f"step count: {len(rb.buffer)}")

step count: 23


In [34]:
step_count = 0
for r in rb.step_list:
    step_count += len(r)

print(f"check step count: {step_count}")
print(f"round count: {len(rb.step_list)}")

check step count: 23
round count: 8


In [7]:
test = [1, 2, 3]
# test.clear()

In [26]:
test

[1, 2, 3]

In [27]:
list(test)

[1, 2, 3]

In [10]:
queue = collections.deque(maxlen=5)
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue.append(5)
queue.append(6)

In [11]:
queue

deque([2, 3, 4, 5, 6], maxlen=5)

In [12]:
queue.extend([7, 8, 9])

In [13]:
queue

deque([5, 6, 7, 8, 9], maxlen=5)

In [14]:
list(queue)

[5, 6, 7, 8, 9]

In [19]:
buffer = collections.deque(maxlen = 5)
buffer.append(["a", "ab", 1, 1.0])
buffer.append(["bfd", "aba", 2, 32.0])
buffer.append(["ad", "ab", 3, 423.3])
buffer.append(["aa", "ab", 4, 13.0])
buffer.append(["ad", "ab", 5, 1.0])

In [22]:
transitions = random.sample(buffer, 2)
transitions

[['bfd', 'aba', 2, 32.0], ['aa', 'ab', 4, 13.0]]

In [27]:
states, actions, rewards, dones = zip(*transitions)

In [28]:
states

('bfd', 'aa')

In [29]:
actions

('aba', 'ab')

In [30]:
rewards

(2, 4)

In [31]:
dones

(32.0, 13.0)

In [34]:
[1] * 3

[1, 1, 1]

In [36]:
min(2, 3)

2

In [29]:
t1 = (1, 2, 3)
# t1[0] = 10
t_list = list(t1)
t_list[0] = 10 
tuple(t_list)

(10, 2, 3)

In [30]:
t_list

[10, 2, 3]

In [12]:
for i, v in enumerate(range(1, 0, -1)):
    print(i, v)

0 1


In [21]:
t = 4
left_bound = 2
for i, v in enumerate(range(t, left_bound, -1)):
    print(i, v)

0 4
1 3


In [25]:
t = 2
right_bound = 4
for i, v in enumerate(range(t, right_bound)):
    print(i + 1, v + 1)

1 3
2 4


In [54]:
arr = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
result = np.sum(arr, axis = 0)
result

array([ 9, 12, 15])

In [55]:
arr1 = np.array([1, 1, 1])
result + arr1

array([10, 13, 16])

In [56]:
test_arr = [0, 2, 3]
for t, a in zip(test_arr, arr1):
    print(t, a)

0 1
2 1
3 1


In [15]:
for i, v in enumerate(range(12, 10, -1)):
    print(i, v)

0 12
1 11


In [16]:
for i, v in enumerate(range(12, 14)):
    print(i, v)

0 12
1 13


In [35]:
for round in rb.step_list:
    print(len(round))

2
2
2
2
9
2
2
2


In [36]:
eposide_step_list = rb.step_list[1]
eposide_step_list

[['RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
  [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.04040404040404041,
   0.010101010101010102,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0

In [37]:
final_red_step = eposide_step_list[-1]
final_capture_list = final_red_step[6]
win = 0
if "K" in final_capture_list:
    win = -1
elif "k" in final_capture_list:
    win = 1
final_red_step[5] = True  # done
final_red_step[4] = win

In [38]:
eposide_step_list

[['RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
  [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.04040404040404041,
   0.010101010101010102,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0

In [39]:
steps_data = pd.DataFrame(eposide_step_list, columns = ['state', "pis", "action", "next_state", "raw_reward", "done", "chapture_list", "chapture_reward", "re_reward"])

In [40]:
steps_data

state  \
0  RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c...   
1  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...   

                                                 pis action  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.040...   f0e1   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   h2g2   

                                          next_state  raw_reward   done  \
0  RNBAK1BcR/4A4/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c...           0  False   
1  RNBAc1B1R/4A4/1C4C2/P1P1P1P1P/9/9/p1p1p1p1p/1c...          -1   True   

  chapture_list  chapture_reward  re_reward  
0           [N]             -2.0      -92.8  
1           [K]           -100.0      -92.8

In [24]:
Round.redistribute_reward(eposide_step_list)

step_count: 7
t: 0, left - right: 0 - 2
t: 1, left - right: 0 - 3
t: 2, left - right: 0 - 4
t: 3, left - right: 1 - 5
t: 4, left - right: 2 - 6
t: 5, left - right: 3 - 6
t: 6, left - right: 4 - 6
reward_mat: [[ -1.8     -1.8     -1.62     0.       0.       0.       0.    ]
 [ -0.639   -0.639   -0.639   -0.5751   0.       0.       0.    ]
 [ -3.4749  -3.861   -3.861   -3.861   -3.4749   0.       0.    ]
 [  0.       0.       0.       0.       0.       0.       0.    ]
 [  0.       0.       0.       0.       0.       0.       0.    ]
 [  0.       0.       0.      -1.8549  -2.061   -2.061   -2.061 ]
 [  0.       0.       0.       0.     -79.38   -88.2    -88.2   ]]
addition_rewards: [ -5.9139  -6.3     -6.12    -6.291  -84.9159 -90.261  -90.261 ]


[('RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
  [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.04040404040404041,
   0.010101010101010102,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0

In [41]:
import time

time.time()

1694960374.6260138

In [2]:
agent = DQN(ACTION_DIM, LEARNING_RATE, GAMMA, EPSILON_G, TARGET_UPDATE_COUNT, DEVICE)
rb = ReplayBuffer.load_from_dir("../output/data")

In [40]:
rb.step_size(), rb.round_size()

(1767, 362)

In [41]:
# model_path = train_off_policy_agent(agent, 60, rb, BATCH_SIZE)

In [42]:
batch_s, batch_a, batch_r, batch_ns, batch_d = rb.sample(BATCH_SIZE)

In [43]:
transition_dict = {'states': batch_s, 'actions': batch_a, 'next_states': batch_ns, 'rewards': batch_r, 'dones': batch_d}

In [44]:
batch_s

('1cBAKAr2/2R6/9/P1P3P1c/9/8P/p1p1p1p1p/8n/9/rnbakab2',
 'RNBAKABNR/9/1C5C1/P1P1c1P1P/9/9/p1p1p1p1p/1c7/9/rnbakabnr',
 'rCB2A1c1/4K4/6C1B/P1P1c1P1P/9/9/p1p1p1p1p/6n2/9/rnbakab2',
 'RNBAKAB1R/9/1C4NC1/P1P1P1P1P/9/9/p1p1p1p1p/1c2c4/9/rnbakabnr',
 'RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
 'RNBAKA1cR/9/1C2B2C1/P1P1P1P1P/9/9/p1p1p1p1p/1c7/9/rnbakabnr',
 'RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
 'R1BAKABNR/Cc7/1C7/P1P1c1P2/9/8P/p1p1p1p1p/6n2/9/rnbakab1r',
 '2c4r1/1C7/4K3B/P1P1c1P1P/5C3/9/p1p3p1p/6n2/9/rnbakab2',
 'RNBAKABNR/9/1C7/P1P1c1P1P/3C5/9/p1p1p1p1p/1c4n2/9/rnbakabr1',
 'RNBAKABNR/9/1C5C1/P1P1c1P1P/9/9/p1p1p1p1p/1c7/9/rnbakabnr',
 '1cB1K3c/R8/1C2B4/P1P4CP/4P1P2/9/p1p1p1p1p/6n2/9/rnbakab1r',
 'R1BA1A1N1/4K3R/2p1C2c1/P3P4/5nP1P/9/p3p1p1p/5cn2/9/r1ba1kbr1',
 'RNBAKABNR/9/1C5C1/P1P1P1P1P/9/9/p1p1p1p1p/1c5c1/9/rnbakabnr',
 '1cBAKABNR/9/RC5C1/P1P1c1P1P/9/9/p1p1p1p1p/9/9/rnbakabnr',
 'RNBAKABNR/9/1C2C4/P1P1P1P1P/9/9/p1p1p1p1p/1c2c4/9/rnbakabnr',
 'R

In [45]:
planes = [convert_board_to_tensor(state) for state in transition_dict['states']]
states_tensor = torch.stack(planes, dim = 0).to(DEVICE)

In [46]:
states_tensor.shape

torch.Size([64, 14, 10, 9])

In [47]:
batch_a

('c1f1',
 'g0e2',
 'g2g1',
 'c0e2',
 'g0i2',
 'h2g2',
 'b2d2',
 'a1a6',
 'f4f5',
 'd4b4',
 'g0e2',
 'e2g0',
 'a0a1',
 'h2e2',
 'b2b5',
 'e2h2',
 'g0e2',
 'c0e2',
 'g0e2',
 'a1a6',
 'g0i2',
 'h0f1',
 'g0e2',
 'h2e2',
 'g0e2',
 'a1c1',
 'a2c1',
 'e2h2',
 'i0i2',
 'e1g1',
 'g0e2',
 'e2h2',
 'b2b4',
 'g0i2',
 'h2e2',
 'h2e2',
 'h2e2',
 'h2e2',
 'h2e2',
 'h2e2',
 'c0e2',
 'h2e2',
 'b2d2',
 'h2e2',
 'h2e2',
 'a0a2',
 'e2h2',
 'e2h2',
 'h2e2',
 'e2h2',
 'a0a1',
 'h2e2',
 'a1c1',
 'e2h2',
 'e2h2',
 'g0e2',
 'g0e2',
 'e2h2',
 'h2e2',
 'b7b3',
 'g0e2',
 'd6d1',
 'i2f2',
 'e2f2')

In [48]:
actions_index_list = []
for action in transition_dict['actions']:
    action_idx = ACTIONS_2_INDEX[action]
    actions_index_list.append(action_idx)
actions_index_tensor = torch.tensor(actions_index_list).view(-1, 1).to(DEVICE)
actions_index_tensor.shape

torch.Size([64, 1])

In [49]:
actions_index_tensor

tensor([[ 449],
        [2075],
        [1429],
        [2056],
        [2060],
        [1661],
        [ 247],
        [  32],
        [1244],
        [ 757],
        [2075],
        [2074],
        [   8],
        [1659],
        [ 257],
        [ 950],
        [2075],
        [2056],
        [2075],
        [  32],
        [2060],
        [1631],
        [2075],
        [1659],
        [2075],
        [  20],
        [  57],
        [ 950],
        [1843],
        [ 926],
        [2075],
        [ 950],
        [ 256],
        [2060],
        [1659],
        [1659],
        [1659],
        [1659],
        [1659],
        [1659],
        [2056],
        [1659],
        [ 247],
        [1659],
        [1659],
        [   9],
        [ 950],
        [ 950],
        [1659],
        [ 950],
        [   8],
        [1659],
        [  20],
        [ 950],
        [ 950],
        [2075],
        [2075],
        [ 950],
        [1659],
        [ 371],
        [2075],
        [ 815],
        

In [50]:
rewards = torch.tensor(transition_dict['rewards'], dtype = torch.float).view(-1, 1).to(DEVICE)
rewards.shape

torch.Size([64, 1])

In [51]:
next_planes = [convert_board_to_tensor(state) for state in transition_dict['next_states']]
next_states_tensor = torch.stack(next_planes, dim = 0).to(DEVICE)
next_states_tensor.shape

torch.Size([64, 14, 10, 9])

In [52]:
dones = torch.tensor(transition_dict['dones'], dtype = torch.float).view(-1, 1).to(DEVICE)
dones.shape

torch.Size([64, 1])

In [53]:
model_output = agent.q_net(states_tensor)
model_output.shape

torch.Size([64, 2086])

In [54]:
q_values = agent.q_net(states_tensor).gather(1, actions_index_tensor)
q_values.shape

torch.Size([64, 1])

In [71]:
target_q_values_tensor = agent.target_q_net(next_states_tensor)
batch_size = target_q_values_tensor.shape[0]

next_states_str_list = transition_dict['next_states']
# next_state = next_states_str_list[0]
# alist = get_legal_actions(next_state, PLAYER_RED)

# print(next_state)
# print(alist)
legal_actions_list = [get_legal_actions(next_state, PLAYER_RED) for next_state in next_states_str_list]
target_q_values_formatted = torch.zeros((batch_size, ACTION_DIM))
for i in range(batch_size):
    legal_actions = legal_actions_list[i]
    for action in legal_actions:
        action_idx = ACTIONS_2_INDEX[action]
        target_q_values_formatted[i][action_idx] = target_q_values_tensor[i][action_idx]

target_q_values_formatted.max(1)[0].view(-1, 1)
# agent.target_q_net(next_states_tensor).max(1)[0].view(-1, 1).shape

tensor([[0.7966],
        [0.9936],
        [0.9174],
        [0.8816],
        [0.9409],
        [0.6893],
        [0.8038],
        [0.7481],
        [0.9792],
        [1.5763],
        [0.9936],
        [0.8743],
        [1.1035],
        [0.8259],
        [1.2192],
        [1.2536],
        [0.9936],
        [0.7112],
        [0.9936],
        [0.7481],
        [0.7270],
        [0.7621],
        [0.9936],
        [0.8259],
        [0.9936],
        [1.0533],
        [0.9823],
        [1.2536],
        [0.8826],
        [0.6783],
        [0.9936],
        [1.2536],
        [0.9881],
        [0.9283],
        [0.8259],
        [0.8259],
        [0.8259],
        [0.8259],
        [0.8259],
        [0.8259],
        [0.8368],
        [0.8259],
        [1.3167],
        [0.8259],
        [0.8259],
        [1.1674],
        [1.2536],
        [1.2536],
        [0.8259],
        [1.2536],
        [1.1714],
        [0.8259],
        [1.0935],
        [1.2536],
        [1.2536],
        [0

In [ ]:
num_epoch = 100
batch_s, batch_a, batch_r, batch_ns, batch_d = rb.sample(BATCH_SIZE)
transition_dict = {'states': batch_s, 'actions': batch_a, 'next_states': batch_ns, 'rewards': batch_r, 'dones': batch_d}
for i in range(num_epoch):
    start_time = time.time()
    loss = agent.update(transition_dict)

    LOGGER.info(f'progress={i + 1} / {num_epoch} | loss = {loss:.3f} | elapse={time.time() - start_time:.3f} s')

[2023-09-20 00:17:13,338][hoho_dqn.py][line:195][INFO] Update Target network!
[2023-09-20 00:17:13,367][179702317.py][line:8][INFO] progress=1 / 100 | loss = 4422.107 | elapse=3.170 s
[2023-09-20 00:17:14,014][179702317.py][line:8][INFO] progress=2 / 100 | loss = 4280.424 | elapse=0.646 s
[2023-09-20 00:17:14,656][179702317.py][line:8][INFO] progress=3 / 100 | loss = 4183.297 | elapse=0.641 s
[2023-09-20 00:17:15,295][179702317.py][line:8][INFO] progress=4 / 100 | loss = 4131.954 | elapse=0.638 s
[2023-09-20 00:17:15,941][179702317.py][line:8][INFO] progress=5 / 100 | loss = 4092.021 | elapse=0.644 s
[2023-09-20 00:17:16,579][179702317.py][line:8][INFO] progress=6 / 100 | loss = 4062.752 | elapse=0.638 s
[2023-09-20 00:17:17,218][179702317.py][line:8][INFO] progress=7 / 100 | loss = 4032.421 | elapse=0.638 s
[2023-09-20 00:17:17,863][179702317.py][line:8][INFO] progress=8 / 100 | loss = 4011.912 | elapse=0.645 s
[2023-09-20 00:17:18,509][179702317.py][line:8][INFO] progress=9 / 100 | l

[2023-09-20 00:18:01,529][179702317.py][line:8][INFO] progress=75 / 100 | loss = 3809.064 | elapse=0.652 s
[2023-09-20 00:18:02,185][179702317.py][line:8][INFO] progress=76 / 100 | loss = 3808.134 | elapse=0.656 s
[2023-09-20 00:18:02,836][179702317.py][line:8][INFO] progress=77 / 100 | loss = 3807.454 | elapse=0.651 s


In [9]:
b1 = torch.tensor([[1, 2, 3], [2, 5, 6], [7, 8, 9]])
b2 = torch.ones((3, 3))
torch.concat([b1, b2], dim = 0)

tensor([[1., 2., 3.],
        [2., 5., 6.],
        [7., 8., 9.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
b1 = torch.ones((64, 14, 10, 9))
b2 = torch.ones((64, 14, 10, 9))
torch.concat([b1, b2], dim = 1).shape

torch.Size([64, 28, 10, 9])